# P1: OEREB Import Nutzungsplanung
name: Run P1.import.NuPl

on:
  workflow_dispatch:
    inputs:
      xtf_filename:
        description: "Input XTF-Datei"
        required: true
        type: string

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Download GeoPackage as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: geopackage
          path: ./_data/so.arp.nutzungsplanung_kommunal.gpkg

      - name: Run Schemaimport
        run: java -jar ./_Runners/ili2gpkg/ili2gpkg-5.2.2-SNAPSHOT.jar --dbfile ./_data/so.arp.nutzungsplanung_kommunal.gpkg --createBasketCol --defaultSrsCode 2056 --log ./_logs/01_schemaimport_nupl.log --schemaimport --models SO_ARP_Nutzungsplanung_Publikation_20201005 

      - name: Run Dataimport
        run: java -jar ./_Runners/ili2gpkg/ili2gpkg-5.2.2-SNAPSHOT.jar --dbfile ./_data/so.arp.nutzungsplanung_kommunal.gpkg --defaultSrsCode 2056 --dataset ${{ inputs.xtf_filename }} --log ./_logs/01_dataimport_nupl.log --replace ./_data/${{ inputs.xtf_filename }}

      - name: Upload Logs
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: _logs/

      - name: Upload GeoPackage as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: geopackage
          path: ./_data/so.arp.nutzungsplanung_kommunal.gpkg

  download-artifact:
    runs-on: ubuntu-latest
    needs: run-script  # Warte auf den vorherigen Job
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download GeoPackage Artifact
        uses: actions/download-artifact@v4
        with:
          name: geopackage
          path: ./_data

      - name: Verify Download
        run: ls -l ./_data  # Überprüft, ob die Datei vorhanden ist
