# P2: AV Import
name: Run P2.import

on:
  #push:
  #  branches:
  #    - main
  #pull_request:
  #  branches:
  #    - main
  workflow_dispatch: 

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install requests
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run GetFromGeopilotSTAC
        run: |
          source venv/bin/activate
          python ./P2.import/STACDownload.py

      - name: Run Schemaimport
        run: java -jar ./_Runners/ili2gpkg/ili2gpkg-5.2.2-SNAPSHOT.jar --dbfile ./_data/so.agi.amtliche_vermessung.gpkg --createBasketCol --defaultSrsCode 2056 --log ./_logs/01_schemaimport_nupl.log --schemaimport --models SO_ARP_Nutzungsplanung_Publikation_20201005 

      - name: Upload GeoPackage as Artifact (Initial)
        uses: actions/upload-artifact@v4
        with:
          name: geopackage
          path: ./_data/av_current.xtf

      - name: Run Dataimport
        run: java -jar ./_Runners/ili2gpkg/ili2gpkg-5.2.2-SNAPSHOT.jar --dbfile ./_data/so.agi.amtliche_vermessung.gpkg --defaultSrsCode 2056 --log ./_logs/01_dataimport_nupl.log --replace ./_data/av_current.xtf

      - name: Upload Logs
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: logs/